config/routes.rb
Rails.application.routes.draw do
  
  root 'public#public_page'

  get 'home',:to => 'home#index',:as => '/home'
  get 'login' ,:to => 'home#login',:as =>'/login'
  get 'logout',:to => 'home#logout',:as => '/logout'
  post 'home/attempt_login'
  get 'dispatch/index'

  #admin specific routes
  post 'admins/attempt_login'
  get 'admins/logout'
  get 'admin',:to => 'admins#login',:as => '/admin'
  get 'admins/admin_menu'

  #staff specific routes
 post 'staffs/attempt_login'
  get 'staffs/logout'
  get 'staffs/login'

  #super_admin specific routes
  post 'super_admins/attempt_login'
  get 'super_admins/login'
  get 'super_admins/logout'
  get 'super_admins/super_admins_menu'




  
  resources :admins do
     member do
        get :delete
     end
  end
  resources :staffs do
     member do
        get :delete
     end
  end
  resources :super_admins do
     member do
        get :delete
     end
  end
  resources :emergencies
  resources :clients
  resources :hospitals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  # EMAIL_REGEX = /\A[a-z0-9._%+-]+[a-z0-9.-]+\.[a-z]{2,4}\z/i
  # validates_presence_of :email
  # validates_length_of :email,:maximum => 100
  # validates_format_of :email,:with => EMAIL_REGEX
  has_secure_password
end

app/controllers/super_admins_controller.rb
class SuperAdminsController < ApplicationController
	before_action :confirm_super_admin_is_logged_in ,except: [:login,:logout,:attempt_login]
	before_action :set_super_admin ,only: [:show,:update,:destroy,:edit]
	def index
		@super_admin = SuperAdmin.all
	end

	def super_admins_menu
	end

	def show
	end

	def new
		@super_admin = SuperAdmin.new
	end

	def create
		@super_admin = SuperAdmin.new(super_admin_params)
		if @super_admin.save
           flash[:notice] = 'Super Admin added successfully'
           redirect_to super_admins_path
       else
       	flash[:notice] = 'Super Admin was not created'
		end
	end

	def edit
	end

	def update
	end

	def destroy
		@super_admin.destroy
		respond_to do | format |
          format.html{redirect_to super_admins_path ,notice: 'Super Admin successfully deleted'}
          format.json{head :no_content}
		end
	end

	def login
	end

	def attempt_login
		if params[:username].present? && params[:password].present?
            super_admin = SuperAdmin.where(:username => params[:username]).first
            if super_admin
            	authorize_super_admin = super_admin.authenticate(params[:password])
            end
		end

		if authorize_super_admin
            session[:super_admin_id] = authorize_super_admin.id
            flash[:notice] = 'You are logged in'
            redirect_to super_admins_super_admins_menu_path

        else
        	flash.now[:notice] = 'Wrong username/password combination'
        	redirect_to super_admins_login_path
		end
	end

	def logout
		session[:super_admin_id] = nil
		flash[:notice] = 'You are logged out'
		redirect_to super_admins_login_path
	end

	private
    

	#set super_admin 
	def set_super_admin
      @super_admin = SuperAdmin.find(params[:id])
	end

	#super admin params
	def super_admin_params
       params.require(:super_admin).permit(:first_name,:last_name,:username,:email,:password)
	end


end

app/helpers/super_admins_helper.rb
module SuperAdminsHelper
end

app/views/super_admins/_form.html.erb
<div class="container">
  <%= form_with( model: super_admin,locale: true ) do |form| %>
     <% if super_admin.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(client.errors.count, "error") %> prohibited this super_admin from being saved:</h2>

	      <ul>
	      <% super_admin.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
     <% end %>

      <div class="container-fluid jumbotron">
  	        <div class="row">
		    	<div class="form-group col-md-4">
		    		<%= form.label :first_name %>
		    		<%= form.text_field :first_name,id: :first_name ,autofocus: true,class: 'form-control'%>
		    	</div>
		    </div>

		    <div class="row">
		    	<div class="form-group col-md-4">
		    		<%= form.label :last_name %>
		    		<%= form.text_field :last_name,id: :last_name ,autofocus: true,class: 'form-control'%>
		    	</div>
		    </div>
		    	
		    <div class="row">
		    	<div class="form-group col-md-4">
		    		<%= form.label :username %>
		    		<%= form.text_field :username,id: :username ,autofocus: true,class: 'form-control'%>
		    	</div>
		    </div>
		    	
		    <div class="row">
		    	<div class="form-group col-md-4">
		    		<%= form.label :email %>
		    		<%= form.text_field :email,id: :email ,autofocus: true,class: 'form-control'%>
		    	</div>
		    </div>
		    	
		    <div class="row">
		    	<div class="form-group col-md-4">
		    		<%= form.label :password %>
		    		<%= form.text_field :password,id: :password ,autofocus: true,class: 'form-control'%>
		    	</div>
		    </div>
       </div>

       <%= button_tag(type: 'submit',class: 'btn btn-primary btn-lg button-drop') do %>
          <span class="glyphicon glyphicon-floppy-disk"></span>save
	   <% end %> 

  <% end %>
</div>

app/views/super_admins/edit.html.erb
<div class="container">
	<legend><h1>Edit Super Admin Details:</h1></legend>
	<div class="jumbotron">
		<%= render 'form', super_admin: @super_admin %>
	</div>

	<%= link_to 'Show', @super_admin,class: 'btn btn-default' %> |
	<%= link_to 'Back', super_admins_path %>
</div>

app/views/super_admins/index.html.erb
<div class="container">
  <p class="alert alert-success"><%= notice %></p>

   <%= link_to new_super_admin_path,class: 'btn btn-info btn-lg client-new' do %>
     <span class="gyphicon glyphicon-plus"></span>Add Super-Admin
   <% end %>
    <br>
    <br>
    <br>
    <br>
   <div class="jumbotron">
     <table class="table table-hover">
     	<thead>
     	  <tr>
     		<th>Super Admin ID:</th>
     		<th>First Name</th>
     		<th>Last Name</th>
     		<th>Username</th>
     		<th>Email</th>
     	  </tr>
     	</thead>
     	<tbody>
     		<% @super_admin.each do |superadmin| %>
               <tr>
               	 <td><%= superadmin.id %></td>
               	 <td><%= superadmin.first_name %></td>
               	 <td><%= superadmin.last_name %></td>
               	 <td><%= superadmin.username %></td>
               	 <td><%= superadmin.email %></td>
               	 <td><%= link_to 'Show',superadmin,class: 'btn btn-success' %></td>
               	 <td><%= link_to 'Edit',edit_super_admin_path(superadmin),class: 'btn btn-info' %></td>
               	 <td><td><%= link_to 'Delete',superadmin,method: :delete,data: {confirm: 'Are you sure?'},class: 'btn btn-danger' %></td></td>
               </tr>
     		<% end%>
     	</tbody>
     </table>   	
   </div>
</div>

app/views/super_admins/login.html.erb
<div class="container">
	<p id="notice" class="alert alert-success"><%= notice %></p>
	<p><h3><em><strong>Login as Super Admin:</strong></em></h3></p>
	<div class="jumbotron">
		<%= form_tag(super_admins_attempt_login_path ,:method => :post) do %>

		    <div class="row">
		    	<div class="form-group col-md-4">
		    		<%= label_tag(:username) %>
		            <%= text_field_tag(:username,params[:username],autofocus: true,class: 'form-control') %>
		    	</div>
		    </div>

	        <div class="row">
	        	<div class="form-group col-md-4">
	        		<%= label_tag(:password) %>
	                <%= password_field_tag(:password,autofocus: true,class: 'form-control') %>
	        	</div>
	        </div>
	    <%= submit_tag("Log In") %>
	<% end %>
	</div>
</div>

app/views/super_admins/new.html.erb
<div class="container">
	<h1>New Super Admin</h1>
	<%= render 'form',super_admin: @super_admin %>

	<%= link_to 'Back' ,super_admins_path,class: 'btn btn-link' %>
</div>

app/views/super_admins/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

   <div class="client-details">
    <p>
      <strong>Super Admin Number: </strong>
        <%= @super_admin.id %>
    </p>

    <p>
      <strong>First_name:</strong>
      <%= @super_admin.first_name %>
    </p>

    <p>
      <strong>Last_name:</strong>
      <%= @super_admin.last_name %>
    </p>

    <p>
      <strong>Username:</strong>
      <%= @super_admin.email %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @super_admin.email %>
    </p>

   </div>
  <%= link_to 'Edit', edit_super_admin_path(@super_admin),:class => 'btn btn-default' %> |
  <%= link_to 'Back', super_admins_path,:class => 'btn btn-link' %>
</div>

app/views/super_admins/super_admins_menu.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>


<p>Welcome to the super admins menu</p>
<%= link_to 'Add Super Admin',new_super_admin_path %>