config/routes.rb
Rails.application.routes.draw do
  
  root 'public#public_page'

  get 'home',:to => 'home#index',:as => '/home'
  get 'login' ,:to => 'home#login',:as =>'/login'
  get 'logout',:to => 'home#logout',:as => '/logout'
  post 'home/attempt_login'
  get 'dispatch/index'

  #admin specific routes
  post 'admins/attempt_login'
  get 'admins/logout'
  get 'admin',:to => 'admins#login',:as => '/admin'
  get 'admins/admin_menu'

  #staff specific routes
 post 'staffs/attempt_login'
  get 'staffs/logout'
  get 'staffs/login'

  #super_admin specific routes
  post 'super_admins/attempt_login'
  get 'super_admins/login'
  get 'super_admins/logout'
  get 'super_admins/super_admins_menu'




  
  resources :admins do
     member do
        get :delete
     end
  end
  resources :staffs do
     member do
        get :delete
     end
  end
  resources :super_admins do
     member do
        get :delete
     end
  end
  resources :emergencies
  resources :clients
  resources :hospitals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  
  # EMAIL_REGEX = /\A[a-z0-9._%+-]+[a-z0-9.-]+\.[a-z]{2,4}\z/i
  # validates_presence_of :email
  # validates_length_of :email,:maximum => 100
  # validates_format_of :email,:with => EMAIL_REGEX
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :emergencies
	validates :fname,:lname,:phone,:status,presence: { message: "This fields is compulsory" }

end

app/models/emergency.rb
class Emergency < ApplicationRecord
  belongs_to :client ,:dependent => :destroy

  geocoded_by :address
  after_validation :geocode

  validates :address,:description,:client_id ,presence: {message: "This field is compulsory"}

end

app/models/hospital.rb
class Hospital < ApplicationRecord
	geocoded_by :address
	after_validation :geocode

	validates :address,:name,:phone,:email ,presence: {message: 'This field is compulsory'}
end

app/models/staff.rb
class Staff < ApplicationRecord
	# EMAIL_REGEX = /\A[a-z0-9._%+-]+[a-z0-9.-]+\.[a-z]{2,4}\z/i
 #  validates_presence_of :email
 #  validates_length_of :email,:maximum => 100
 #  validates_format_of :email,:with => EMAIL_REGEX
  has_secure_password
end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  # EMAIL_REGEX = /\A[a-z0-9._%+-]+[a-z0-9.-]+\.[a-z]{2,4}\z/i
  # validates_presence_of :email
  # validates_length_of :email,:maximum => 100
  # validates_format_of :email,:with => EMAIL_REGEX
  has_secure_password
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :admin_confirm_logged_in ,only: [:admin_menu]
	before_action :confirm_super_admin_is_logged_in,only:[:index,:new,:create,:edit,:update]
	before_action :set_admin, only: [:show,:update,:edit,:destroy] 
	#list all admins
	def index
		@admin_list = Admin.all
	end

	def admin_menu
	end


	def new
		@admin = Admin.new
	end

    #create new admin
	def create
		@admin = Admin.new(admin_params)
        if @admin.save
          flash[:notice] = 'Admin has been successfully created'
          redirect_to admins_path
      else
      	flash[:notice] = 'New admin was not created'
		end
	end

	def show
	end

	def edit
	end

	def update

	end

    #destroy admin access
	def destroy
	  @admin.destroy
	  respond_to do |format|
         format.html{ redirect_to admins_path, notice:'successfully deleted admin user' }
         format.json {head :no_content}
	  end

	end

	def login
		#render admin_login form
	end
	def attempt_login
		#handle the login
		if params[:username].present? && params[:password].present?
           admin_found = Admin.where(:username => params[:username]).first

           if admin_found
             authorized_admin = admin_found.authenticate(params[:password])
           end
		end

		if authorized_admin
           session[:admin_id] = authorized_admin.id
           flash[:notice] = 'You are logged in'
           redirect_to admins_admin_menu_path
       else
       	   flash.now[:notice] = "invalid username/password combination"
       	   render('login')
		end
	end

    #admin logout
	def logout
		session[:admin_id] = nil
		flash[:notice] = 'Logged out'
		redirect_to admin_path
	end

	private
     #a method to confirm if a user is logged in before we could do anything
	

	def set_admin
      @admin = Admin.find(params[:id])
	end
    
    def admin_params
       params.require(:admin).permit(:first_name,:last_name,:username,:email,:password)
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :confirm_logged_in ,only: [:index]

	def index
        emergency_last = Emergency.last
        @hospitals_nearest = Hospital.near([emergency_last.latitude,emergency_last.longitude],5,:units => :km)
	end

	def login
	end

	def attempt_login
		if params[:username].present? && params[:password].present?
	        approved_staff = Staff.where(:username => params[:username]).first
		    if approved_staff
	             authorized_staff = approved_staff.authenticate(params[:password])
		    end
		end

		if authorized_staff
	       session[:staff_id] = authorized_staff.id
	       flash[:notice] = 'You are logged in'
	       redirect_to home_path

	   else
	   	  flash.now[:notice] = 'Invalid username/password combination'
	   	  redirect_to login_path
		end
	end

	def logout
		session[:staff_id] = nil
		flash[:notice] = 'You are logged out'
		redirect_to login_path
	end

	private
    
    def confirm_logged_in
      unless session[:staff_id]
         flash[:notice] = 'You must be logged in'
         redirect_to login_path
      end
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def home
  	# @emergency = Emergency.last
  	# @hash = Gmaps4rails.build_markers(@emergency) do |emergency, marker|
   #    marker.lat emergency.latitude
   #    marker.lng emergency.longitude
   #  end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def  load_emergency_form
      render(:partial => 'emergencies/form',:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder])
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dispatch_helper.rb
module DispatchHelper
end

app/helpers/emergencies_helper.rb
module EmergenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/super_admins_helper.rb
module SuperAdminsHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin,local: true) do | form | %>
    
    <div>
    	<%= form.label :FirstName %>
    	<%= form.text_field :first_name %>
    </div>
        
    <div>
    	<%= form.label :LastName %>
    	<%= form.text_field :last_name %>
    </div>

     <div>
    	<%= form.label :Email %>
    	<%= form.text_field :email %>
    </div>

     <div>
    	<%= form.label :Username %>
    	<%= form.text_field :username %>
    </div>

     <div>
    	<%= form.label :DefaultPassword %>
    	<%= form.text_field :password %>
    </div>

    <%= button_tag(type: 'submit',:class => 'btn btn-primary btn-lg btn-drop') do %>
       <span class="glyphicon glyphicon-floppy-disk"></span>save
    <% end %>
<% end %>

app/views/admins/admin_menu.html.erb
<p>welcome to the admin menu page</p>
<%= link_to 'Add Client',clients_path %>
<%= link_to 'Add Hospital',hospitals_path %>
<%= link_to 'View Client list',clients_path %>

app/views/admins/edit.html.erb
<div class="container-fluid">
	<legend><h1>Edit Admin Details</h1></legend>
	 <div class="jumbotron">
	 	<%= render 'form',admin: @admin %>
	 </div>
	 <%=link_to 'Show',@admin,class: 'btn btn-default' %> |
	 <%= link_to 'Back',admin_path %>
</div>

app/views/admins/index.html.erb
<div class="container">
	<p id="notice" class="alert alert-danger"><%= notice %></p>
	<%= link_to new_admin_path,:class => 'btn btn-info btn-lg client-new' do %>
       <span class="glyphicon glyphicon-plus"></span>Add Admin
	<% end %>

	<h2>Admins</h2>
	<div class="jumbotron">
		<table class="table table-hover bordered">
		<thead>
			<th>Admin ID</th>
			<th>First name</th>
			<th>Last name</th>
			<th>Email</th>
		</thead>
		<tbody>
			<% @admin_list.each do |admin_details| %>
              <tr>
				<td><%= admin_details.id %></td>
				<td><%= admin_details.first_name %></td>
				<td><%= admin_details.last_name %></td>
				<td><%= admin_details.email %></td>
				<td><%= link_to 'Show',admin_details,:class => 'btn btn-success' %></td>
				<td><%= link_to 'Edit',edit_admin_path(admin_details),:class => 'btn btn-info' %></td>
				<td><%= link_to 'Destroy' ,admin_details,method: :delete ,data: { confirm: 'Are you sure?'},:class => 'btn btn-danger' %></td>
			  </tr>
            <% end %>
		</tbody>
	</table>
	</div>
</div>

app/views/admins/login.html.erb
<div class="container">
	<p id="notice" class="alert alert-success"><%= notice %></p>
	<p><h3><em><strong>Login as Admin:</strong></em></h3></p>
	<div class="jumbotron">
		<%= form_tag(admins_attempt_login_path ,:method => :post) do %>

		    <div class="row">
		    	<div class="form-group col-md-4">
		    		<%= label_tag(:username) %>
		            <%= text_field_tag(:username,params[:username],autofocus: true,class: 'form-control') %>
		    	</div>
		    </div>

	        <div class="row">
	        	<div class="form-group col-md-4">
	        		<%= label_tag(:password) %>
	                <%= password_field_tag(:password,autofocus: true,class: 'form-control') %>
	        	</div>
	        </div>
	    <%= submit_tag("Log In") %>
	<% end %>
	</div>
</div>

app/views/admins/new.html.erb
<div class="container">
	<%= render 'form',admin: @admin %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project111</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <div id="rapide-logo">
     <p><%= image_tag('logo.png',:size => '150x100' ,:alt => 'logo' )%></p>
  </div>

 


<div class="container-fluid">
   <%= yield %>
</div> 

<script>
    var $MapAndForm = $("#emergency-register-form,#map");

    $(document).ready(function(){
          //code goes in here
        $('#emergency-switcher').on('click',function(){
          $MapAndForm.toggleClass('show-form');
        });
    });
</script>
  </body>
</html>

app/views/layouts/public.html.erb
<style>
	.patrick-image{
		margin-left: 30px;
		float: left;
		width: 40%;
	}
	.redirection-message{
		float: right;
		font-size: 50px;
		font-family: ubuntu;
		width: 60%;
	}
	.redirect-link{
		color: red;
	}
</style>
<div class="container">
	<div class="patrick-image">
		<p><%= image_tag('patrick.jpg',alt: 'A funny pictrure of patrick') %></p>
	</div>
	<div class="redirection-message">
		<p>If you've been redirected here please leave this page by clicking <span class="redirect-link"><em>here</em></span></p>
		<p>Otherwise you know what to do.</p>
	</div>
</div>