config/routes.rb
Rails.application.routes.draw do
  
  root 'public#public_page'

  get 'home',:to => 'home#index',:as => '/home'
  get 'login' ,:to => 'home#login',:as =>'/login'
  get 'logout',:to => 'home#logout',:as => '/logout'
  post 'home/attempt_login'
  get 'dispatch/index'

  #admin specific routes
  post 'admins/attempt_login'
  get 'admins/logout'
  get 'admin',:to => 'admins#login',:as => '/admin'
  get 'admins/admin_menu'

  #staff specific routes
 post 'staffs/attempt_login'
  get 'staffs/logout'
  get 'staffs/login'

  #super_admin specific routes
  post 'super_admins/attempt_login'
  get 'super_admins/login'
  get 'super_admins/logout'
  get 'super_admins/super_admins_menu'




  
  resources :admins do
     member do
        get :delete
     end
  end
  resources :staffs do
     member do
        get :delete
     end
  end
  resources :super_admins do
     member do
        get :delete
     end
  end
  resources :emergencies
  resources :clients
  resources :hospitals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :emergencies
	validates :fname,:lname,:phone,:status,presence: { message: "This fields is compulsory" }

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :admin_confirm_logged_in
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:ClientNumber, :fname, :lname, :phone, :email, :status, :insurance)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid jumbotron">
     <div class="row">
        <div class="form-group col-md-4">
          <%= form.label :fname %>
          <%= form.text_field :fname, id: :client_fname,autofocus: true,:class => "form-control" %>
        </div>
     </div>

   <div class="row">
      <div class="form-group col-md-4">
        <%= form.label :lname %>
        <%= form.text_field :lname, id: :client_lname,autofocus: true,:class => "form-control"  %>
      </div>
   </div>

   <div class="row">
      <div class="form-group col-md-4">
        <%= form.label :phone %>
        <%= form.text_area :phone, id: :client_phone,autofocus: true,:class => "form-control"  %>
      </div>
   </div>

    <div class="row">
      <div class="form-group col-md-4">
        <%= form.label :email %>
        <%= form.text_field :email, id: :client_email,autofocus: true,:class => "form-control"  %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-4">
        <%= form.label :status %>
        <%= form.text_field :status, id: :client_status,autofocus: true,:class => "form-control"  %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-4">
        <%= form.label :insurance %>
        <%= form.text_area :insurance, id: :client_insurance,autofocus: true,:class => "form-control"  %>
      </div>
    </div>
    <!-- <div class="actions">
      <%= form.submit %>
    </div> -->

    <%= button_tag(type: 'submit',class: 'btn btn-primary btn-lg button-drop') do %>
        <span class="glyphicon glyphicon-floppy-disk"></span>save
    <% end %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="container">
	<legend><h1>Edit Client Details:</h1></legend>
	<div class="jumbotron">
		<%= render 'form', client: @client %>

		<%= link_to 'Show', @client %> |
		<%= link_to 'Back', clients_path %>
	</div>
</div>

app/views/clients/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div>
  <%= link_to new_client_path ,:class => 'btn btn-info btn-lg client-new' do %>
    <span class="glyphicon glyphicon-plus"></span>New Client
  <% end %>
 </div>

 <h1>Clients</h1>
   <div class="jumbotron">
      <table class='table table-hover'>
        <thead>
          <tr>
            <th>Client Number</th>
            <th>Fname</th>
            <th>Lname</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Status</th>
            <th>Insurance</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @clients.each do |client| %>
            <tr>
              <td><%= client.id %></td>
              <td><%= client.fname %></td>
              <td><%= client.lname %></td>
              <td><%= client.phone %></td>
              <td><%= client.email %></td>
              <td><%= client.status %></td>
              <td><%= client.insurance %></td>
              <td><%= link_to 'Show', client,:class => 'btn btn-success' %></td>
              <td><%= link_to 'Edit', edit_client_path(client) ,:class => 'btn btn-info'%></td>
              <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } ,:class => 'btn btn-danger'%></td>
            </tr>
          <% end %>
        </tbody>
    </table>

    <br>
   </div>
    <%= link_to 'Back To DashBoard',admins_admin_menu_path,class: 'btn btn-default btn-small' %>
</div>

app/views/clients/new.html.erb
<div class="container">
	<h1>New Client</h1>

	<%= render 'form', client: @client %>

	<%= link_to 'Back', clients_path,:class => 'btn btn-link' %>
</div>

app/views/clients/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

   <div class="client-details">
    <p>
      <strong>Client Number: </strong>
        <%= @client.id %>
    </p>

    <p>
      <strong>Fname:</strong>
      <%= @client.fname %>
    </p>

    <p>
      <strong>Lname:</strong>
      <%= @client.lname %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @client.phone %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @client.email %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @client.status %>
    </p>

    <p>
      <strong>Insurance:</strong>
      <%= @client.insurance %>
    </p>
   </div>
  <%= link_to 'Edit', edit_client_path(@client),:class => 'btn btn-default' %> |
  <%= link_to 'Back', clients_path,:class => 'btn btn-link' %>
</div>