config/routes.rb
Rails.application.routes.draw do
  
  root 'public#public_page'

  get 'home',:to => 'home#index',:as => '/home'
  get 'login' ,:to => 'home#login',:as =>'/login'
  get 'logout',:to => 'home#logout',:as => '/logout'
  post 'home/attempt_login'
  get 'dispatch/index'

  #admin specific routes
  post 'admins/attempt_login'
  get 'admins/logout'
  get 'admin',:to => 'admins#login',:as => '/admin'
  get 'admins/admin_menu'

  #staff specific routes
 post 'staffs/attempt_login'
  get 'staffs/logout'
  get 'staffs/login'

  #super_admin specific routes
  post 'super_admins/attempt_login'
  get 'super_admins/login'
  get 'super_admins/logout'
  get 'super_admins/super_admins_menu'




  
  resources :admins do
     member do
        get :delete
     end
  end
  resources :staffs do
     member do
        get :delete
     end
  end
  resources :super_admins do
     member do
        get :delete
     end
  end
  resources :emergencies
  resources :clients
  resources :hospitals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hospital.rb
class Hospital < ApplicationRecord
	geocoded_by :address
	after_validation :geocode

	validates :address,:name,:phone,:email ,presence: {message: 'This field is compulsory'}
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :admin_confirm_logged_in
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
    @geojson = Array.new

    emergency_last = Emergency.last
    @hospitals_nearest = Hospital.near([emergency_last.latitude,emergency_last.longitude],5,:units => :km)

      @hospitals_nearest.each do |hospital_near|
         @geojson << {
              type: 'Feature',
              geometry: {
                type: 'Point',
                coordinates: [hospital_near.longitude, hospital_near.latitude]
              },
              properties: {
                name: hospital_near.name,
                address: hospital_near.address,
                contact: hospital_near.phone,
                BusType: 'hospital',
                popupContent: "#{hospital_near.address} and contact #{hospital_near.phone}",
                :'marker-color' => '#00607d',
                :'marker-symbol' => 'circle',
                :'marker-size' => 'medium'
              }
            }
      end
      respond_to do |format|
         format.html
         format.json{ render json: @geojson }
      end
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:address, :latitude, :longitude, :name, :phone, :email)
    end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital, local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
   <div class="container-fluid jumbotron">
      <div class="row">
        <div class="form-group col-md-4">
          <%= form.label :address %>
          <%= form.text_field :address, id: :hospital_address,autofocus: true,class: 'form-control' %>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-md-4"
          <%= form.label :latitude %>
          <%= form.text_field :latitude, id: :hospital_latitude,autofocus: true,class: 'form-control' %>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-md-4">
          <%= form.label :longitude %>
          <%= form.text_field :longitude, id: :hospital_longitude,autofocus: true,class: 'form-control' %>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-md-4">
          <%= form.label :name %>
          <%= form.text_area :name, id: :hospital_name,autofocus: true,class: 'form-control' %>
        </div>
      </div>

      <div class="row">
         <div class="form-group col-md-4">
          <%= form.label :phone %>
          <%= form.text_field :phone, id: :hospital_phone,autofocus: true,class: 'form-control' %>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-md-4">
          <%= form.label :email %>
          <%= form.text_field :email, id: :hospital_email,autofocus: true,class: 'form-control' %>
        </div>
      </div>

      <!-- <div class="actions">
        <%= form.submit %>
      </div>  --> 
      
      <%= button_tag(type: 'submit',class: 'btn btn-primary btn-lg button-drop') do %>
        <span class="glyphicon glyphicon-floppy-disk"></span>save
      <% end %>

   </div>

<% end %>

app/views/hospitals/edit.html.erb
<div class="container">
  <h1>Edit Hospital Details:</h1>
  <%= render 'form', hospital: @hospital %>

  <%= link_to 'Show', @hospital,:class => 'btn btn-default' %> |
  <%= link_to 'Back', hospitals_path,:class => 'btn btn-link' %>
</div>

app/views/hospitals/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

   <%= link_to  new_hospital_path,:class => 'btn btn-lg btn-success hospital-new'  do %>
      <span class="glyphicon glyphicon-plus"></span>Hospital
   <% end %>

  <h1>Member Hospitals</h1>

<div class="jumbotron">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Address</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @hospitals.each do |hospital| %>
        <tr>
          <td><%= hospital.address %></td>
          <td><%= hospital.latitude %></td>
          <td><%= hospital.longitude %></td>
          <td><%= hospital.name %></td>
          <td><%= hospital.phone %></td>
          <td><%= hospital.email %></td>
          <td><%= link_to 'Show', hospital ,:class => 'btn btn-success'%></td>
          <td><%= link_to 'Edit', edit_hospital_path(hospital),:class => 'btn btn-info' %></td>
          <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <br>
  <%= link_to 'Back To DashBoard',admins_admin_menu_path,class: 'btn btn-default btn-small' %>

</div

app/views/hospitals/new.html.erb
<div class="container">
   <h1>Register New Hospital</h1>
   <%= render 'form', hospital: @hospital %>
   <%= link_to 'Back', hospitals_path,:class => 'btn btn-link' %>
</div>

app/views/hospitals/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Address:</strong>
    <%= @hospital.address %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= @hospital.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= @hospital.longitude %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @hospital.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @hospital.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @hospital.email %>
  </p>

  <%= link_to 'Edit', edit_hospital_path(@hospital) %> |
  <%= link_to 'Back', hospitals_path %>

</div>